import 'r.dart';

const Map<String, String> enLanguagePackage = {
  R.Mywallet: "My wallet",
  R.Setting: "Setting",
  R.Signout: "Sign out",
  R.Darkmode: "Dark mode",
  R.Entertheemailaccountthatyouwanttorecovery:
      "Enter the email account that you want to recovery",
  R.SENDCODE: "SEND CODE",
  R.Resetpassword: "Reset password",
  R.Newpassword: "New password",
  R.Confirmpassword: "Confirm password",
  R.CONFIRM: "CONFIRM",
  R.A4charactercodehasbeensenttotheemail:
      "A 4-character code has been sent to the email",
  R.VERIFY: "VERIFY",
  R.Didntreceiveanycode: "Didn't receive any code?",
  R.Signin: "Sign in",
  R.Password: "Password",
  R.SIGNIN: "SIGN IN",
  R.Forgotpassword: "Forgot password?",
  R.Signup: "Sign up",
  R.SIGNUP: "SIGNUP",
  R.ManageyourfinanceseffectivelywithMoneyKeeper:
      "Manage your finances effectively with MoneyKeeper",
  R.Cutunnecessaryexpenses: "Cut unnecessary expenses",
  R.Increasesavingssteadilyeverymonth: "Increase savings steadily every month",
  R.Manageitallinoneplace: "Manage it all in one place",
  R.SIGNUPFORFREE: "SIGN UP FOR FREE",
  R.Home: "Home",
  R.Transaction: "Transaction",
  R.Report: "Report",
  R.Account: "Account",
  R.Lastweek: "Last week",
  R.Thisweek: "This week",
  R.Lastmonth: "Last month",
  R.Thismonth: "This month",
  R.Nextmonth: "Next month",
  R.Totalbalance: "Total balance",
  R.Seemore: "See more",
  R.All: "All",
  R.Detail: "Detail",
  R.Week: "Week",
  R.Month: "Month",
  R.Totalexpenseofthisweek: "Total expense of this week",
  R.Totalexpenseofthismonth: "Total expense of this month",
  R.Mostexpense: "Most expense",
  R.Recently: "Recently",
  R.Addwallet: "Add wallet",
  R.Editwallet: "Edit wallet",
  R.Walletname: "Wallet name",
  R.Balance: "Balance",
  R.Notincludeintotalbalance: "Not include in total balance",
  R.Createanewwalletanddonotincludeitintototalbalance:
      "Create a new wallet and do not include it into total balance",
  R.ADDNEW: "ADD NEW",
  R.DELETETHISWALLETFOREVER: "DELETE THIS WALLET FOREVER",
  R.UPDATE: "UPDATE",
  R.Including: "Including",
  R.Week1: 'Week 1',
  R.Week2: 'Week 2',
  R.Week3: 'Week 3',
  R.Week4: 'Week 4',
  R.Expensedetail: "Expense detail",
  R.Totalexpense: "Total expense",
  R.Incomedetail: "Income detail",
  R.Totalincome: "Total income",
  R.IncomeandExpense: "Income and Expense",
  R.Totalleft: "Total left",
  R.Income: "Income",
  R.Expense: "Expense",
  R.Newtransaction: "New transaction",
  R.Save: "Save",
  R.Selectcategory: "Select category",
  R.Note: "Note",
  R.Edittransaction: "Edit transaction",
  R.Viewreportofthisperiod: "View report of this period",
  R.Pleaseenteralltheinformation: "Please enter all the information",
  R.Incorectcode: "Incorrect code",
  R.Incorectpassword: "Incorrect password",
  R.Vietnamese: "Vietnamese",
  R.Type: "Type",
  R.ManageCategory: "Category",
  R.Categoryname: "Category name",
  R.Planning: "Planning",
  R.Budget: "Budget",
  R.Afinancial:
      "A financial plan that helps you balance your income and expenses",
  R.Event: "Event",
  R.Createaneventto:
      "Create an event to track a real event, for example a weekend trip",
  R.Running: "Running",
  R.Finished: "Finished",
  R.Addevent: "Add event",
  R.Editevent: "Edit event",
  R.Eventname: "Event name",
  R.Enddate: "End date",
  R.Selectwallet: "Select wallet",
  R.Spent: "Spent",
  R.Markasfinished: "Mark as finished",
  R.Markasunfinished: "Mark as unfinished",
  R.Listoftransaction: "List of transaction",
  R.LoansDebts: "Loans & Debts",
  R.Loan: "Loan",
  R.Debtcollection: "Debt Collection",
  R.Debt: "Debt",
  R.Repayment: "Repayment",
  R.Totalbudget: "Total budgets",
  R.budget: "budget(s)",
  R.Left: "Left",
  R.days: "day(s)",
  R.now: "now",
  R.result: "result",
  R.hour: "hour",
  R.left: "left",
  R.recommendeddaily: "Recommended daily spending",
  R.projectedspending: "Projected spending",
  R.actualspending: "Actual spending",
  R.canSpent: "Amount you can spent",
  R.Groupwallet: "Group wallet",
  R.Totalwallet: "Total wallet",
  R.Standard: "Standard",
  R.Categorylist: "Category list",
  R.instructionofcategorylist:
      "This new wallet's categories will be cloned from the list's categories has been chosen",
  R.RequiredExpense: "Required expense",
  R.NecessaryExpense: "Necessary expense",
  R.Entertainment: "Entertainment",
  R.InvestingOrDebt: "Investing or debt",
  R.Transactioncreatedsuccessfully: "Transaction created successfully",
  R.Walleterror: "Wallet error",
  R.Today: "Today",
  R.Monday: "Monday",
  R.Tuesday: "Tuesday",
  R.Wednesday: "Wednesday",
  R.Thursday: "Thursday",
  R.Friday: "Friday",
  R.Saturday: "Saturday",
  R.Sunday: "Sunday",
  R.Transactioneditedsuccessfully: "Transaction edited successfully",
  R.Deletethistransaction: "Delete this transaction",
  R.Deletethistransactionquesttion: "Delete this transaction?",
  R.Yes: "Yes",
  R.No: "No",
  R.remaining: "Remaining",
  R.newBudget: "New budget",
  R.noneBudget: "No budget currently",
  R.pressPlusBudget: "Press the + button to add budget",
  R.noneTransaction: "There are currently no transactions in this budget",
  R.Notification: "Notification",
  R.Createbudgetsuccessfully: "Create budget successfully",
  R.Deletethisbudgetquestion: "Delete this budget?",
  R.Overspent: "Over spent",
  R.Summary: "Summary",
  R.editBudget: "Edit budget",
  R.editBudgetsuccessfully: "Edit budget successfully",
  R.invitation: "Invitation",
  R.Youhavenewinvite: "You have an new invitation to the group wallet",
  R.Accept: "Accept",
  R.Decline: "Decline",
  R.Addgroupwallet: 'Add group wallet',
  R.editgroupwallet: 'Edit group wallet',
  R.Addmembers: "Enter the email you want to add to the wallet group",
  R.memberGroup: "The members in your wallet group",
  R.Personal: "Personal",
  R.Group: "Group",
  R.Therearecurrentlynoevents: "There are currently no events",
  R.Togglesuccess: "Successfully marked",
  R.Deletethisevent: "Delete this event?",
  R.Oftheevent: "Of the event?",
  R.Email: "Email",
  R.Earned: "Earned",
  R.Cannotdeletestandard: "Cannot delete standard's category",
  R.WithMember: "With member?",
  R.yourOwnerWallet: 'You are already the wallet owner',
  R.emailNotExits: 'User does not exist',
  R.emailEnteredThat: 'You already entered that',
  R.Seenall: 'Seen all',
  R.from: 'from',
};
