import 'r.dart';

const Map<String, String> viLanguagePackage = {
  R.Mywallet: "Ví của tôi",
  R.Setting: "Cài đặt",
  R.Signout: "Đăng xuất",
  R.Darkmode: "Chế độ ban đêm",
  R.Entertheemailaccountthatyouwanttorecovery:
      "Nhập địa chỉ email mà bạn muốn khôi phục mật khẩu",
  R.SENDCODE: "GỬI MÃ",
  R.Resetpassword: "Khôi phục mật khẩu",
  R.Newpassword: "Mật khẩu mới",
  R.Confirmpassword: "Xác nhận mật khẩu",
  R.CONFIRM: "XÁC NHẬN",
  R.A4charactercodehasbeensenttotheemail:
      "Một mã gồm 4 ký tự đã được gửi đến email",
  R.VERIFY: "XÁC MINH",
  R.Didntreceiveanycode: "Không nhận được mã?",
  R.Signin: "Đăng nhập",
  R.Password: "Mật khẩu",
  R.SIGNIN: "ĐĂNG NHẬP",
  R.Forgotpassword: "Quên mật khẩu?",
  R.Signup: "Đăng ký",
  R.SIGNUP: "ĐĂNG KÝ",
  R.ManageyourfinanceseffectivelywithMoneyKeeper:
      "Quản lý tài chính hiệu quả với MoneyKeeper",
  R.Cutunnecessaryexpenses: "Cắt giảm những chi phí không cần thiết",
  R.Increasesavingssteadilyeverymonth: "Gia tăng tiết kiệm đều đặn hàng tháng",
  R.Manageitallinoneplace: "Quản lý tất cả ở một nơi",
  R.SIGNUPFORFREE: "ĐĂNG KÝ MIỄN PHÍ",
  R.Home: "Trang chủ",
  R.Transaction: "Thu chi",
  R.Report: "Thống kê",
  R.Account: "Tài khoản",
  R.Lastweek: "Tuần trước",
  R.Thisweek: "Tuần này",
  R.Lastmonth: "Tháng trước",
  R.Thismonth: "Tháng này",
  R.Nextmonth: "Tháng sau",
  R.Totalbalance: "Tổng số dư",
  R.Seemore: "Xem thêm",
  R.All: "Toàn bộ",
  R.Detail: "Chi tiết",
  R.Week: "Tuần",
  R.Month: "Tháng",
  R.Totalexpenseofthisweek: "Tổng chi tuần này",
  R.Totalexpenseofthismonth: "Tổng chi tháng này",
  R.Mostexpense: "Chi nhiều nhất",
  R.Recently: "Gần đây",
  R.Addwallet: "Thêm ví mới",
  R.Editwallet: "Chỉnh sửa ví",
  R.Walletname: "Tên ví",
  R.Balance: "Số dư",
  R.Notincludeintotalbalance: "Không bao gồm vào ví tổng",
  R.Createanewwalletanddonotincludeitintototalbalance:
      "Tạo ví này và không bao gồm số dư của nó vào ví tổng",
  R.ADDNEW: "THÊM MỚI",
  R.DELETETHISWALLETFOREVER: "XOÁ VĨNH VIỄN VÍ NÀY",
  R.UPDATE: "CẬP NHẬT",
  R.Including: "Bao gồm",
  R.Week1: 'Tuần 1',
  R.Week2: 'Tuần 2',
  R.Week3: 'Tuần 3',
  R.Week4: 'Tuần 4',
  R.Expensedetail: "Chi tiết khoản chi",
  R.Totalexpense: "Tổng chi",
  R.Incomedetail: "Chi tiết khoản thu",
  R.Totalincome: "Tổng thu",
  R.IncomeandExpense: "Thu và Chi",
  R.Totalleft: "Còn lại",
  R.Income: "Khoản thu",
  R.Expense: "Khoản chi",
  R.Newtransaction: "Giao dịch mới",
  R.Save: "Lưu",
  R.Selectcategory: "Chọn danh mục",
  R.Note: "Ghi chú",
  R.Edittransaction: "Sửa giao dịch",
  R.Viewreportofthisperiod: "Xem thống kê kỳ này",
  R.Pleaseenteralltheinformation: "Vui lòng điền đủ thông tin",
  R.Incorectcode: "Mã không hợp lệ",
  R.Incorectpassword: "Mật khẩu không khớp",
  R.Vietnamese: "Tiếng Việt",
  R.Type: "Khoản",
  R.ManageCategory: "Danh mục",
  R.Categoryname: "Tên danh mục",
  R.Planning: "Kế hoạch",
  R.Budget: "Ngân sách",
  R.Afinancial:
      "Một kế hoạch tài chính giúp bạn cân bằng khoản thu và khoản chi của mình",
  R.Event: "Sự kiện",
  R.Createaneventto:
      "Tạo một sự kiện để theo dõi một sự kiện có thực nào đó, ví dụ như đi du lịch cuối tuần",
  R.Running: "Đang áp dụng",
  R.Finished: "Đã kết thúc",
  R.Addevent: "Thêm sự kiện",
  R.Editevent: "Sửa sự kiện",
  R.Eventname: "Tên sự kiện",
  R.Enddate: "Ngày kết thúc",
  R.Selectwallet: "Chọn ví",
  R.Spent: "Đã chi",
  R.Markasfinished: "Đánh dấu kết thúc",
  R.Markasunfinished: "Đánh dấu chưa kết thúc",
  R.Listoftransaction: "Danh sách thu chi",
  R.LoansDebts: "Khoản vay & nợ",
  R.Loan: "Cho vay",
  R.Debtcollection: "Thu nợ",
  R.Debt: "Đi vay",
  R.Repayment: "Trả nợ",
  R.Totalbudget: "Tổng ngân sách",
  R.budget: "ngân sách",
  R.Left: "Còn lại",
  R.days: "ngày",
  R.now: "nay",
  R.result: "kết quả",
  R.hour: "giờ",
  R.left: "còn lại",
  R.recommendeddaily: "Đề nghị chi tiêu hằng ngày",
  R.projectedspending: "Chi tiêu dự kiến",
  R.actualspending: "Chi tiêu thực tế",
  R.canSpent: "Số tiền bạn có thể chi",
  R.Groupwallet: "Ví nhóm",
  R.Totalwallet: "Ví tổng",
  R.Standard: "Tiêu chuẩn",
  R.Categorylist: "Danh sách mục",
  R.instructionofcategorylist:
      "Danh mục của ví mới này sẽ được sao chép toàn bộ từ danh mục của nhóm danh mục mà bạn chọn",
  R.RequiredExpense: "Chi tiêu bắt buộc",
  R.NecessaryExpense: "Chi tiêu cần thiết",
  R.Entertainment: "Vui chơi giải trí",
  R.InvestingOrDebt: "Đầu tư & nợ",
  R.Transactioncreatedsuccessfully: "Tạo giao dịch thành công",
  R.Walleterror: "Ví lỗi",
  R.Today: "Hôm nay",
  R.Monday: "Thứ hai",
  R.Tuesday: "Thứ ba",
  R.Wednesday: "Thứ tư",
  R.Thursday: "Thứ năm",
  R.Friday: "Thứ sáu",
  R.Saturday: "Thứ bảy",
  R.Sunday: "Chủ nhật",
  R.Transactioneditedsuccessfully: "Cập nhật giao dịch thành công",
  R.Deletethistransaction: "Xoá giao dịch này",
  R.Deletethistransactionquesttion: "Xoá giao dịch này?",
  R.Yes: "Có",
  R.No: "Không",
  R.remaining: "Còn lại",
  R.newBudget: "Ngân sách mới",
  R.noneBudget: "Hiện không có ngân sách nào",
  R.pressPlusBudget: "Chạm nút + phía dưới để thêm ngân sách",
  R.noneTransaction: "Hiện tại không có giao dịch nào trong ngân sách này",
  R.Notification: "Thông báo",
  R.Createbudgetsuccessfully: "Tạo ngân sách thành công",
  R.Deletethisbudgetquestion: "Xoá ngân sách này?",
  R.Overspent: "Chi tiêu quá mức",
  R.Summary: "Tổng kết",
  R.editBudget: "Sửa ngân sách",
  R.editBudgetsuccessfully: "Sửa ngân sách thành công",
  R.invitation: "Lời mời",
  R.Youhavenewinvite: "Bạn có một lời mời vào ví nhóm",
  R.Accept: "Đồng ý",
  R.Decline: "Từ chối",
  R.Addgroupwallet: 'Thêm ví nhóm mới',
  R.editgroupwallet: 'Chỉnh sửa ví nhóm mới',
  R.Addmembers: "Nhập email mà bạn muốn thêm vào ví nhóm",
  R.memberGroup: "Các thành viên trong ví nhóm của bạn",
  R.Personal: "Cá nhân",
  R.Group: "Nhóm",
  R.Therearecurrentlynoevents: "Hiện tại không có sự kiện nào",
  R.Togglesuccess: "Đánh dấu thành công",
  R.Deletethisevent: "Xoá sự kiện này?",
  R.Oftheevent: "Thuộc sự kiện?",
  R.Email: "Tài khoản",
  R.Earned: "Thu được",
  R.Cannotdeletestandard: "Không thể xoá danh mục tiêu chuẩn",
  R.WithMember: "Với thành viên?",
  R.yourOwnerWallet: 'Bạn đã là chủ ví',
  R.emailNotExits: 'Email không tồn tại',
  R.emailEnteredThat: 'Email đã được nhập',
  R.Seenall: 'Đã xem',
  R.from: 'từ',
};
